#!/bin/sh

set -e

# Function adaption of ldd misc-modules/module_load script
misc_modules_load() {
	module=$1
	device=$1
	mode="664"

	if [ $# -ne 1 ]; then
		echo "Usage: $0 <module>"
		exit 1
	fi

	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	modprobe $module || exit 1

	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
		rm -f /dev/${device}
		mknod /dev/${device} c $major 0
		chgrp $group /dev/${device}
		chmod $mode /dev/${device}
	fi
}

# Function adaption of ldd misc-modules/module_unload script
misc_modules_unload() {
	module=$1
	device=$1

	if [ $# -ne 1 ]; then
		echo "Usage: $0 <module>"
		exit 1
	fi

	rmmod $module || exit 1

	rm -f /dev/${device}
}

# Function adaption of ldd scull/scull_load script
scull_load() {
	module="scull"
	device="scull"
	mode="664"

	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	modprobe $module || exit 1

	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

	rm -f /dev/${device}[0-3]
	mknod /dev/${device}0 c $major 0
	mknod /dev/${device}1 c $major 1
	mknod /dev/${device}2 c $major 2
	mknod /dev/${device}3 c $major 3
	ln -sf ${device}0 /dev/${device}
	chgrp $group /dev/${device}[0-3]
	chmod $mode /dev/${device}[0-3]

	rm -f /dev/${device}pipe[0-3]
	mknod /dev/${device}pipe0 c $major 4
	mknod /dev/${device}pipe1 c $major 5
	mknod /dev/${device}pipe2 c $major 6
	mknod /dev/${device}pipe3 c $major 7
	ln -sf ${device}pipe0 /dev/${device}pipe
	chgrp $group /dev/${device}pipe[0-3]
	chmod $mode /dev/${device}pipe[0-3]

	rm -f /dev/${device}single
	mknod /dev/${device}single c $major 8
	chgrp $group /dev/${device}single
	chmod $mode /dev/${device}single

	rm -f /dev/${device}uid
	mknod /dev/${device}uid c $major 9
	chgrp $group /dev/${device}uid
	chmod $mode /dev/${device}uid

	rm -f /dev/${device}wuid
	mknod /dev/${device}wuid c $major 10
	chgrp $group /dev/${device}wuid
	chmod $mode /dev/${device}wuid

	rm -f /dev/${device}priv
	mknod /dev/${device}priv c $major 11
	chgrp $group /dev/${device}priv
	chmod $mode /dev/${device}priv
}

# Function adaption of ldd scull/scull_unload script
scull_unload() {
	module="scull"
	device="scull"

	rmmod $module || exit 1

	rm -f /dev/${device} /dev/${device}[0-3]
	rm -f /dev/${device}priv
	rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
	rm -f /dev/${device}single
	rm -f /dev/${device}uid
	rm -f /dev/${device}wuid
}

case "$1" in
	start)
		scull_load
		misc_modules_load faulty
		modprobe hello
		;;
	stop)
		scull_unload
		misc_modules_unload faulty
		rmmod hello
		;;
	*)
		echo "Usage $0 {start|stop}"
		exit 1
esac

exit 0
